source 'https://rubygems.org'

gem 'sinatra',            '~> 1.4'
gem 'sinatra-contrib',    '~> 1.4'
gem 'mongo',              '~> 1.9' 
gem 'bson',               '~> 1.9'
gem 'bson_ext',           '~> 1.9'
gem 'mongoid',            '~> 2.4'
gem 'mongoid-pagination', '~> 0.1'
gem 'redcarpet',          '~> 2.1'
gem 'thin',               '~> 1.5'
gem 'roo',                '~> 1.0'
gem 'docify',             '~> 1.0'